### ISSUE TITLE
Place cameras in the simulation 

### ISSUE THREAD

**Issue by BriandBlalock** [RoboticsClubatUCF/Bowser#10]
~Put either the current set up of webcams or models of the Intel D435i's the ZED stereo camera onto the robot in the simulation.~

Task: create a **new** Bowser model with two generic Gazebo-plugin cameras facing to the two opposite sides (not front-back).

**Comment by BriandBlalock** [comment]
Here is the link to the gazebo plugin https://github.com/intel/gazebo-realsense

**Comment by wesfletch** [comment]
Done. New Bowser model with two side-facing cameras is called bowser2.
