### ISSUE TITLE
Research alternative mapping packages

### ISSUE THREAD

**Issue by chickenfromouterspace** [RoboticsClubatUCF/Bowser#20]
Document a comparison of multiple mapping packages. Determine which mapping package best suits the needs of IGVC.

**Comment by chickenfromouterspace** [comment]
Look into rtabmap.

**Comment by BriandBlalock** [comment]
I will also be looking into this as part of my senior design

**Comment by BriandBlalock** [comment]
Rtab-map info 
Ros wiki: http://wiki.ros.org/rtabmap_ros
Github/website: http://introlab.github.io/rtabmap/

**Comment by BriandBlalock** [comment]
THe RTAB full paper. It also does a comparison of multiple other mapping methods.  

https://introlab.3it.usherbrooke.ca/mediawiki-introlab/images/7/7a/Labbe18JFR_preprint.pdf

**Comment by BriandBlalock** [comment]
➤ Robotics Club at UCF commented:

We are having some preliminary success with RTAB-Map and the ZED camera. We have successfully created a (limited) 3D occupancy grid
