### ISSUE TITLE
We need to test the motor with a similar load to the actual robot

### ISSUE THREAD

**Issue by ianw2560** [RoboticsClubatUCF/Bowser#29]
We need to test the motor with a similar load to the actual robot (i.e. ~220 lbs) and calculate the effect on the RPM. We should probably set up some sort of equation to relate the load on the motor to the RPM.

**Comment by chickenfromouterspace** [comment]
[Motor Microbasic test.md](https://github.com/RoboticsClubatUCF/Bowser/blob/master/catkin_ws/src/bowser_nav/doc/Roboteq%20Microbasic/Motor%20Microbasic%20Test.md) provides the preliminary tests of the motor without load.

We will want to repeat this test once we have the motors mounted to the robot frame to add significant weight.
