### ISSUE TITLE
Add VLP-16 to Simulation

### ISSUE THREAD

**Issue by BriandBlalock** [RoboticsClubatUCF/Bowser#9]
Replace the current hokuyo lidar in the simulation to the VLP-16

**Comment by wesfletch** [comment]
It doesn't look like the library you showed me is compatible with our version of Gazebo (9)

**Comment by BriandBlalock** [comment]
I think it may be possible to put the VLP-32 into Gazebo , then spin it manually.

**Comment by wesfletch** [comment]
Did with the HDL32, which I believe spins manually at roughly 28HZ #27
